### ISSUE TITLE
Connection Issues: Validate if the following scenario can be handled

### ISSUE THREAD

**Issue by AndreasKl** [AndreasKl/reactive-spring-session-postgres#7]
With the following script:
```
#!/bin/bash

for i in {1..5000} 
do
  echo "loop $i"
  psql -h localhost -p 39889 -U postgres \
       -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = 'session' AND pid <> pg_backend_pid();"
  sleep 0.1

done
```

I am able to reproduce the following stacktrace, when putting the test service under load.

```
2019-07-09 22:36:14.619 ERROR 7402 --- [ntloop-thread-0] o.s.w.s.adapter.HttpWebHandlerAdapter    : [7f7cda81] 500 Server Error for HTTP GET "/"

io.vertx.core.VertxException: closed
	at io.reactiverse.pgclient.impl.SocketConnection.handleClose(SocketConnection.java:316) ~[reactive-pg-client-0.11.4.jar:0.11.4]
	at io.reactiverse.pgclient.impl.SocketConnection.handleClosed(SocketConnection.java:295) ~[reactive-pg-client-0.11.4.jar:0.11.4]
	at io.vertx.core.net.impl.ConnectionBase.handleClosed(ConnectionBase.java:317) ~[vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.net.impl.NetSocketImpl.handleClosed(NetSocketImpl.java:357) ~[vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.net.impl.VertxHandler.lambda$channelInactive$4(VertxHandler.java:162) ~[vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) ~[vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43) ~[vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188) ~[vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:180) ~[vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:162) ~[vertx-core-3.7.1.jar:3.7.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:278) ~[netty-handler-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1403) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:912) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:827) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by AndreasKl** [comment]
```
[andreaskluth@localhost wrk]$ ./wrk -H 'Cookie: SESSION=a5610f32-ab55-49fc-9f1f-5ed4ae43f410' -H 'Connection: close'  -d 60s -c 5 --latency -t 3 http://localhost:8080/
Running 1m test @ http://localhost:8080/
  3 threads and 5 connections
^C  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.26ms    2.01ms  28.88ms   77.70%
    Req/Sec   225.18     71.75   454.00     78.98%
  Latency Distribution
     50%    3.70ms
     75%    5.09ms
     90%    6.91ms
     99%   11.17ms
  38105 requests in 0.94m, 11.63MB read
  Socket errors: connect 0, read 399, write 0, timeout 0
  Non-2xx or 3xx responses: 438
Requests/sec:    672.71
Transfer/sec:    210.17KB
```

**Comment by AndreasKl** [comment]
Can't be handled.
